version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ore20140614 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  
    restart: always 

volumes:
  mysql-data:
